### ISSUE TITLE
TypeError: Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by Unisay** [slamdata/purescript-aff#160]
Related to #153

I use `_parTraverse` to run test cases in parallel and have the following error (undeterministically, sometimes it doesn't pop-up)

```
/project/ui-tests/output/Effect.Aff/foreign.js:83
        throw error;
        ^

TypeError: Cannot read property 'constructor' of null
    at Object.isLeft (/project/ui-tests/output/Effect.Aff/index.js:76:112)
    at join (/project/ui-tests/output/Effect.Aff/foreign.js:720:16)
    at /project/ui-tests/output/Effect.Aff/foreign.js:778:19
    at /project/ui-tests/output/Effect.Aff/foreign.js:669:29
    at runEff (/project/ui-tests/output/Effect.Aff/foreign.js:80:7)
    at run (/project/ui-tests/output/Effect.Aff/foreign.js:496:15)
    at /project/ui-tests/output/Effect.Aff/foreign.js:333:19
    at drain (/project/ui-tests/output/Effect.Aff/foreign.js:120:9)
    at Object.enqueue (/project/ui-tests/output/Effect.Aff/foreign.js:141:11)
    at /project/ui-tests/output/Effect.Aff/foreign.js:330:27
```

**Comment by Unisay** [comment]
I am happy to provide information needed:

- Aff version `5.0.0`
- Pulp version `12.3.0`
- purs version `0.12.0`

Unfortunately I am not allowed to share the code needed to reproduce the problem, but here is an excerpt:
```purescript

bootstrapSpec :: Path -> Array Capabilities -> Sel Unit -> Aff Unit
bootstrapSpec path capabilities sel = do
  creds <- BrowserStack.lookupCredentials
  lowerCodensity do
    BrowserStack.proxy creds
    liftCodensity $ parTraverse_ capabilities \caps -> lowerCodensity do
      drv <- driver creds caps
      liftCodensity do
        url <- determineSutUrl path
        Selenium.get drv url
        log "Running test case..."
        runReaderT sel { driver: drv, defaultTimeout: Milliseconds 20000.0 }
        log "Test case completed."```

**Comment by Unisay** [comment]
After changing `parTraverse_` to `forM_` - the error is gone (as well as parallelism)

**Comment by natefaubion** [comment]
Have you tried upgrading to 5.0.1, which has the fix for the bug you referenced?
