### ISSUE TITLE
`peekVar` does not work properly

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-aff#78]
I'm not exactly sure what's happening, but in the new Halogen stuff, when using the new `peekVar`, errors start arising due to an object not having a success property. I'm not sure where it's going wrong as there are some tests in for `peekVar` that show you can still read from a var that has been peeked, etc.

**Comment by jdegoes** [comment]
The problem is [here](https://github.com/slamdata/purescript-aff/blob/master/src/Control/Monad/Aff/Internal.js#L43).

Adding a consumer will consume the value. This means if the value isn't there yet, if it has to wait, then it will consume it; it's only in the case that it's ALREADY there that it won't consume it.

**Comment by hdgarrood** [comment]
I think I hit this issue too, I came up with a minimal reproducing program:

```purescript
module Main where

import Prelude
import Debug.Trace
import Control.Monad.Aff
import Control.Monad.Aff.AVar
import Control.Monad.Eff.Console as EC
import Control.Monad.Aff.Console (log)

main = launchAff do
  var <- makeVar

  forkAff do
    later' 250 do
      wrapped var "peekVar" (peekVar var)
      log "peeked!"

  later' 500 do
    wrapped var "putVar" (putVar var 23.6)

  log "done"

wrapped var msg action = do
  log $ "before: " <> msg
  traceAnyA var
  action
  log $ "after: " <> msg
  traceAnyA var
```

**Comment by hdgarrood** [comment]
Gives this on node 6.9.1:
```
before: peekVar
{ consumers: [], producers: [], error: undefined }
before: putVar
{ consumers: [ { peek: true, success: [Function], error: [Function: voidF] } ],
  producers: [],
  error: undefined }
after: peekVar
{ consumers: [], producers: [], error: undefined }
peeked!
/home/harry/code/aff-test/output/Control.Monad.Eff.Exception/foreign.js:25
    throw e;
    ^

TypeError: Cannot read property 'success' of undefined
    at /home/harry/code/aff-test/output/Control.Monad.Aff.Internal/foreign.js:69:19
    at /home/harry/code/aff-test/output/Control.Monad.Aff/foreign.js:189:17
    at /home/harry/code/aff-test/output/Control.Monad.Aff/foreign.js:195:25
    at /home/harry/code/aff-test/output/Control.Monad.Aff/foreign.js:151:5
    at /home/harry/code/aff-test/output/Control.Monad.Aff/foreign.js:189:17
    at /home/harry/code/aff-test/output/Control.Monad.Aff/foreign.js:195:25
    at /home/harry/code/aff-test/output/Control.Monad.Aff/foreign.js:259:5
    at /home/harry/code/aff-test/output/Control.Monad.Aff/foreign.js:189:17
    at Timeout._onTimeout (/home/harry/code/aff-test/output/Control.Monad.Aff/foreign.js:50:18)
    at ontimeout (timers.js:365:14)
* ERROR: Subcommand terminated with exit code 1
```

**Comment by garyb** [comment]
Yep, that's the one! Thanks for the minimal test case.

**Comment by hdgarrood** [comment]
No problem :) I just edited it actually, I realised that you get the same result if you remove the uses of `later'` so I removed them.
